#!/usr/bin/env node
// Bundles data.js + game.js (the real engine) into an ES module the Worker can
// import, with a DOM/browser stub prelude and a small server API on the end.
// Run after any change to data.js or game.js:  node tools/build-worker.js
'use strict';
const fs = require('fs');
const path = require('path');
const ROOT = path.dirname(__dirname);
const data = fs.readFileSync(path.join(ROOT, 'data.js'), 'utf8');
const game = fs.readFileSync(path.join(ROOT, 'game.js'), 'utf8');

const prelude = `// GENERATED by tools/build-worker.js — do not edit. Rebuild with: node tools/build-worker.js
// ---- browser stubs so the engine runs headless ----
const __el = () => ({ classList: { add() {}, remove() {}, toggle() {} }, dataset: {}, style: {}, disabled: false, options: [],
  value: '', innerHTML: '', textContent: '', className: '', title: '', select() {}, scrollIntoView() {} });
const __EL = __el();
const document = { querySelector: () => __EL, querySelectorAll: () => [], addEventListener() {}, createElement: __el, body: { appendChild() {} } };
const window = {};
const alert = () => {};
const confirm = () => true;
const prompt = () => '';
const setTimeout = () => 0, clearTimeout = () => {}, setInterval = () => 0, clearInterval = () => {};
`;

const api = `
// ---- server API (appended by the bundler) ----
let __flash = null;
flash = msg => { __flash = msg; };

export function createCampaign(entries) {
  // entries: [{ pid, name, tankId }]
  const world = makeWorld(entries.map(e => e.tankId));
  entries.forEach(e => {
    const P = makeInstitution(e.tankId, world);
    P.pid = e.pid; P.name = e.name; P.paper = []; P.paperSeq = 0;
    world.players.push(P);
  });
  while (world.fights.length < TUNE.fightSlots) { W = world; G = world.players[0]; drawFight(); }
  world.players.forEach(P => { G = P; W = world; rollChaos(); logLine(\`\${tankOf(P).name} opens its doors alongside \${entries.length - 1} rival institution(s) run by humans.\`); });
  return world;
}

export function applyAction(world, pid, type, args) {
  W = world; G = world.players.find(p => p.pid === pid);
  if (!G) return { ok: false, msg: 'No such player.' };
  if (G.over) return { ok: false, msg: 'Your institution is out of the race.' };
  __flash = null;
  const a = args || {};
  const n = v => (v === undefined || v === null ? 0 : +v);
  switch (type) {
    case 'hire': actHire(n(a.idx)); break;
    case 'fire': actFire(a.kind, n(a.id)); break;
    case 'court': actCourt(n(a.idx)); break;
    case 'drop': actDrop(a.id); break;
    case 'prog': actProgram(a.id); break;
    case 'commit': actCommit(n(a.f), n(a.s), n(a.amt)); break;
    case 'prospect': actProspect(a.kind); break;
    case 'renew': actRenew(a.id); break;
    case 'lapse': actLapse(a.id); break;
    case 'match': actMatch(n(a.id)); break;
    case 'release': actRelease(n(a.id)); break;
    case 'crisischoice': actCrisis(n(a.idx)); break;
    case 'testify': actTestify(n(a.f)); break;
    case 'serve': actServe(n(a.id)); break;
    case 'keep': actKeepScholar(n(a.id)); break;
    case 'progfocus': actProgFocus(a.tag); break;
    default: return { ok: false, msg: 'Unknown action ' + type };
  }
  return { ok: !__flash, msg: __flash };
}

// the shot clock ran out on a player with a crisis open: take the free exit
export function autoCrisis(world, pid) {
  W = world; G = world.players.find(p => p.pid === pid);
  if (!G || !G.crisis) return;
  const def = CRISES.find(c => c.id === G.crisis.id);
  const affordable = def.choices.map((ch, i) => ({ ch, i, c: crisisCost(ch) }))
    .filter(x => x.c.cash <= G.cash && x.c.inf <= G.influence);
  const choice = affordable.find(x => !(x.c.cash || x.c.inf)) || affordable[0] || { i: 0 };
  actCrisis(choice.i);
}

export function canEnd(world, pid) {
  const P = world.players.find(p => p.pid === pid);
  if (!P) return 'No such player.';
  if (P.over) return null;
  if (P.crisis) return 'Resolve the crisis first.';
  return null;
}

export function resolveMonth(world) {
  W = world;
  const newsBy = {};
  world.players.forEach(p => { newsBy[p.pid] = [...(p.pendingNews || [])]; p.pendingNews = []; });
  const newsFor = p => newsBy[p.pid];
  G = world.players[0];
  monthWorldPre(newsFor);
  world.players.forEach(p => { if (!p.over) withPlayer(p, () => monthPlayer(newsFor(p))); });
  G = world.players[0];
  const ended = monthWorldPost(newsFor);
  world.players.forEach(p => { p.paper = newsBy[p.pid]; p.paperSeq = (p.paperSeq || 0) + 1; });
  return ended;
}

export function viewFor(world, pid) {
  W = world; G = world.players.find(p => p.pid === pid);
  const summaries = world.players.map(p => ({ pid: p.pid, name: p.name, tankId: p.tankId, v: p.stats.won, over: !!p.over }));
  return {
    me: G,
    world: { month: world.month, fights: world.fights, fightDeck: world.fightDeck, rivals: world.rivals,
             leaderShort: world.leaderShort, freeze: world.freeze, players: summaries },
  };
}
`;
const out = prelude + '\n' + data + '\n' + game + '\n' + api;
const dest = path.join(ROOT, 'worker', 'src', 'engine.js');
fs.writeFileSync(dest, out);
console.log(`wrote ${path.relative(ROOT, dest)} (${Math.round(out.length / 1024)} KB)`);
